# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0249c9ec8c24958292aa21be203e2b38"
name = "testAPp"
handle = "testapp-4139"
application_url = "https://c-dns-trustees-image.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_customers,write_discounts,write_price_rules,read_themes,write_themes,write_app_proxy,read_content"

[auth]
redirect_urls = ["https://c-dns-trustees-image.trycloudflare.com/auth/callback", "https://c-dns-trustees-image.trycloudflare.com/auth/shopify/callback", "https://c-dns-trustees-image.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

